accounts/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from .views import loginView, registerView, logoutView

app_name = "accounts"

urlpatterns = [
    path('login', loginView, name="login"),
    path('logout/', logoutView, name="logout"),
    path('register/', registerView, name="register"),
]

blogdjango/urls.py
import django
from django.contrib import admin
from django.urls import path, include
# Configuracion de los archivos estaticos
from django.conf import settings
from django.conf.urls.static import static
# Token
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace="posts")),
    path('api/posts/', include('posts.api.urls', namespace="posts_api")),
    path('comments/', include('comments.urls', namespace="comments")),
    path('api/comments/', include('comments.api.urls', namespace="comments_api")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('api/accounts/', include('accounts.api.urls', namespace="accounts_api")),
    path('api/accounts/token/', obtain_jwt_token),
    path('404/',  django.views.defaults.page_not_found, kwargs={'exception': Exception('Page Not Found!')},name='Error404'),
    path('500/',  django.views.defaults.server_error, name='Error500'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from .views import posts_list, posts_list_user, posts_create, posts_detail, posts_update, posts_delete

app_name = "posts"

urlpatterns = [
    path('', posts_list, name="list"),
    path('user_post/', posts_list_user, name="list_user"),
    path('create/', posts_create, name="create"),
    path('<int:id>/', posts_detail, name="detail"),
    path('<int:id>/edit/', posts_update, name="update"),
    path('<int:id>/delete/', posts_delete, name="delete"),
]

posts/models.py
# Django
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.contrib.contenttypes.models import ContentType

# Django External App
from markdown_deux import markdown

# Project
from .utils import get_read_time
from comments.models import Comment

# Filtro de la lista de post
# Post.objects.all()
# Post.objects.create(user=user, title="Some time")
class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draf=False).filter(publish__lte=timezone.now())

# Actualizar la imagen y guardarla en una carpeta con el id del usuario
def upload_location(instance, filename):
    # filebase, extension = filename.split(".")
    return "%s/%s"%(instance.id, filename)
    # return "%s/%s.%s"%(instance.id, instance.id, extension)

# Create your models here.
class Post(models.Model):
    title       = models.CharField("Titulo",max_length=120)
    slug        = models.SlugField(
                null=True, 
                blank=True,
                unique=True)
    image       = models.ImageField("Imagen", 
                null=True,
                blank=True, 
                upload_to = upload_location,
                height_field="height_field", 
                width_field="width_field", 
                max_length=None)
    height_field= models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content     = models.TextField("Contenido")
    draf        = models.BooleanField("Borrador", default=False)
    publish     = models.DateField("Publicar", auto_now=False, auto_now_add=False)
    read_time   = models.IntegerField(default=0) #models.TimeField(blank=True, null=True) # Asume minutos
    updated     = models.DateTimeField("Fecha de Actualización",auto_now=True, auto_now_add=False)
    timestamp   = models.DateTimeField("Fecha de creación",auto_now=False, auto_now_add=True)
    author      = models.ForeignKey( 
                settings.AUTH_USER_MODEL,
                default = 1,
                on_delete=models.CASCADE,
                verbose_name="Autor")

    # instanciamos el filtro
    objects = PostManager()

    def __unicode__(self):
        return self.title
    
    def __str__(self):
        return self.title

    # URL del post
    def get_absolute_url(self):
    	# return "/posts/%s/"%(self.id)
    	return reverse("posts:detail", kwargs={"id":self.id})
    
    # URL del post API REST
    def get_api_url(self):
        return reverse("posts_api:detail", kwargs={"pk":self.pk})

    def get_markdown(self):
        content = self.content
        return mark_safe(markdown(content))
    
    class Meta:
        ordering = ["-id","-timestamp", "-updated"]

    # Propiedad Comentarios
    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(self)
        return qs
    
    # Crear Comentarios
    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

# Slug funtions
def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string     = instance.get_markdown()
        read_time_var   = get_read_time(html_string)
        instance.read_time = read_time_var

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
# Django
from django import forms
# Django External APP
from pagedown.widgets import PagedownWidget
# Project
from .models import Post

class PostForm(forms.ModelForm):
	# Formulario de Contenido
	content = forms.CharField(label="Contenido",widget=PagedownWidget(show_preview=False))
	# Formulario de Fecha con un select
	publish = forms.DateField(label="Publicar el",widget=forms.SelectDateWidget)
	class Meta:
		model = Post
		fields = ["title", "content", "image", "draf", "publish"]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Blog{% endblock title %}</title>
	<!-- Estilos propios -->
	<link rel="stylesheet" href="{% static 'css/basic.css' %}">
	<style> {% block style %}{% endblock style %} </style>
	<!-- Bootstrap -->
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" crossorigin="anonymous">
	<!-- font-awesome -->
	<link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet" type="text/css">
	<!-- popper -->
	<link rel="stylesheet" href="{% static 'popper/css/popper.css' %}">
	<!-- Extra -->
	{% block head_extra %}{% endblock head_extra %}
	<!-- ICON-->
	<link rel="shortcut icon" href="#">
</head>
<body>
	<div>
		{% include 'navbar.html' %}		
		{% comment %}
		{% endcomment %}
	</div>
	<!-- Mensajes Django -->
	{% include 'mensajes.html' %}
	<!-- Contenido -->
	<div class="container-fluid">
		{% block content %}
		{% endblock %}
	</div>
	<!-- jquery -->
	<script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}" crossorigin="anonymous"></script>
	<!-- popper -->
	<script src="{% static 'popper/js/popper.min.js' %}" crossorigin="anonymous"></script>
	<!-- Marked -->
	<script src="{% static 'marked/marked.js' %}"></script>
	<!-- Comentarios de facebook -->
	<!--
	<div id="fb-root"></div>
	<script async defer src="https://connect.facebook.net/es_ES/sdk.js#xfbml=1&version=v3.2"></script>
	-->
	<!-- Extras -->
	<script>{% block script %}{% endblock script %}</script>
	<script>
	    $(document).ready(function(){
			// Funcion para Render HTML and Markdown en post_detail.html y en post_list.html
			$('.content-markdown').each(function(){
				var content = $(this).text();
				var markedContent = marked(content);
				$(this).html(markedContent);
			});
			$('.content-markdown img').each(function(){
				$(this).addClass("img-thumbnail");
			})
		});
		// Vista previa de contenido de un post al ser editado o creado
		
		// Titulo
		var titleItem = $('#id_title');
		
		function setTitle(value) {
			$('#preview-title').text(value);
		}
		setTitle(titleItem.val());
		// actualizacion automatica de la vista previa del titulo
		titleItem.keyup(function(){
			// console.log($(this).val());
			var newTitle = $(this).val();
			setTitle(newTitle);
		})
		
		// Contenido
		var contentItem = $('#id_content');
		// Funcion para que la imagen del contenido renderize
		function setContent(value) {
			var markedContent = marked(value);
			// Contenido
			$('#preview-content').html(markedContent);
			// Imagen dentro del contenido
			$('#preview-content img').each(function() {
				$(this).addClass("img-thumbnail")
			});
		}
		setContent(contentItem.val())
		// actualizacion automatica de la vista previa del contenido
		contentItem.keyup(function(){
			// console.log($(this).val());
			var newContent = $(this).val();
			setContent(newContent);
		});
		// muestra los comentarios
		$(".comment_reply_btn").on("click",function(e) {
			e.preventDefault();
			console.log("hola")
			$(this).parent().next(".comment_reply").fadeToggle("slow", "linear")
		});
	</script>
</body>
</html>

{% comment "optional note" %}
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. In vitae aperiam deleniti consequuntur aliquam fuga. Voluptate doloribus, adipisci repudiandae amet reiciendis soluta expedita ad dolore commodi. Delectus quaerat itaque iusto.
{% endcomment %}

templates/comment_confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block title %} {{block.super}} | Confirm Delete Comment {% endblock %}

{% block content %}

	<div style="margin: 20px auto; width: 50%;padding: 5px;">				
		<form action="." method="POST">
			{% csrf_token %}
			<h3 style="text-align: center;"> ¿Deseas eliminar el comentario?</h3>
				<p style="color:grey; text-align: center;"> "{{ object.content }}"</p> 
			<div style="margin: 20px auto; text-align: center;">
				<input type="submit" value="Eliminar Comentario" class="btn btn-warning">
				<a href="{{ object.get_absolute_url }}" class="btn btn-primary btn-sm">Cancelar</a>
			</div>
		</form>
	</div>

{% endblock content %}

templates/comment_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block title %} {{block.super}} | Comment Detail {% endblock %}

<style> 
	{% block style %}
	{% endblock style %} 
</style>

{% block content %}
<!-- Comentarios -->
<div 
style="margin-left: 0px; margin-right: 30px; padding-top: 10px;background-color: #eae6e6bd">
	<!-- Muestra Comentarios -->
	<div class="col-sm-12">
		<!-- Titulo -->
		<h2 class="lead" style="padding-left:20px;"> 
			<b style="text-transform: uppercase;">
				Comentarios del post
			</b>
			<small>
				<a href="{% url 'comments:delete' id=comment.id %}">
					<i class="fa fa-trash" aria-hidden="true"></i>
				</a>
			</small>
		</h2>
		<!-- Comentario -->
		<div class="row">
			<div class="col-md-12" style="border-top: 1px solid #d4cbcb">

					<!-- Comentario Padre -->
					<p> {{ comment.content }} </p>
					<small style="color:#483f3f; margin: 0 20px">
						via & {{ comment.author|capfirst }}  |  {{ comment.timestamp|timesince }}
						{% if comment.children.count > 0 %}| {{ comment.children.count }} Comentario{% endif %}{% if comment.children.count > 1 %}s |{% endif %}
						<!-- Los usuarios solo podran eliminar los comentarios que ellos crearon -->
						{% if request.user == comment.author %} |  <a href="{{ comment.get_delete_url }}">Eliminar</a> {% endif %}
					</small>
					<!-- Replica de Comentario -->
					<div>
						{% for child_comment in comment.children %}							
							<blockquote style="padding-left:25px; margin: 0 30px; background-color:#d4cbcb;border-radius:2px;">
								<p> {{ child_comment.content }} </p>
								<p>
									<small style="color:#007bff;">
										via & {{ child_comment.author|capfirst }}  
										|  {{ child_comment.timestamp|timesince }}
										<!-- Los usuarios solo podran eliminar los comentarios que ellos crearon -->
										{% if request.user == child_comment.author %} 
											|  <a href="{{ child_comment.get_delete_url }}">Eliminar</a> 
										{% endif %}			 
									</small>
								</p>
							</blockquote>
						{% endfor %}
						<div class="container">
						{% if request.user.is_authenticated %}				
							<form action="." method="POST">
								{% csrf_token %}
								{{ form|crispy }}
								<input type="hidden" name="parent_id" value=" {{ comment.id }} ">
								<input type="submit" value="Replicar Comentario"
								class="btn btn-primary">
							</form>
						{% else %}
							<p> Debes iniciar sesión para crear un comentario </p>
						{% endif %}
						</div>
					</div>

				<!-- FIN de Comentarios -->
			</div>
		</div>
		<!-- FIN de Row -->
	</div>
	<!-- Fin Muestra Comentarios -->
</div>
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <span class="navbar-text" href="#">BLOG Django</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            
            <li class="nav-item active">
                <a class="nav-link" style="padding: 9px 15px;line-height: 20px;font-size: 22px;" href="{% url 'posts:list' %}">Home</a>
            </li>

            {% if request.user.is_staff %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">admin login</a>
            </li>
            {% endif %}

            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Servicios REST framework</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="nav-link" style="color:#007bff;" href="{% url 'posts_api:list' %}">Post List</a>
                    <a class="nav-link" style="color:#007bff;" href="{% url 'posts_api:create' %}">Create Post</a>
                    <a class="nav-link" style="color:#007bff;" href="{% url 'comments_api:list' %}">Comments List</a>
                    <a class="nav-link" style="color:#007bff;" href="{% url 'comments_api:create' %}">Create Comments</a>
                    {% if request.user.is_staff %}
                        <a class="nav-link" style="color:#007bff;" href="{% url 'accounts_api:login' %}">Iniciar Sesión</a>
                        {% if request.user.is_superuser %}
                            <a class="nav-link" style="color:#007bff;" href="{% url 'accounts_api:register' %}">Registro de Usuarios</a>
                        {% endif %}
                    {% endif %}
                </div>
            </li>
            {% endif %}
        </ul>

        <ul class="navbar-nav mr-auto">
            {% block post_username %}
            {% endblock post_username %}
            <!-- Si el usuario no esta autenticado -->
            {% if not request.user.is_authenticated %}
            <li class="nav-item">
                <a class="btn btn-outline-success" href="{% url 'accounts:login' %}">Iniciar Sesión</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-outline-success" href="{% url 'accounts:register' %}">Registro de Usuario</a>
            </li>
            <!-- Si el usuario esta autenticado -->
            {% else %}
            <li class="nav-item">
                <a class="btn btn-outline-success" href="{% url 'posts:list_user' %}" 
                data-toggle="tooltip" data-placement="bottom" title="Mis Post">
                    {{ request.user|upper }}
                    {% if request.user.is_active %}
                        <span> <small> -activo </small> </span>
                    {% endif %}
                    {% if request.user.is_staff %}
                        <span> <small style="color:#00ffff;"> -staff </small> </span>
                    {% endif %}
                    {% if request.user.is_superuser %}
                        <span> <small style="color:#007bff;"> -superuser </small> </span>
                    {% endif %}
                </a>
            </li>
            <li class="nav-item">
                <a class="btn btn-outline-success" href="{% url 'accounts:logout' %}">Cerrar Sesión</a>
            </li>
            {% endif %}
        </ul>
        {% block post_list %}
        {% endblock post_list %}
    </div>
</nav>

templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block title %} {{block.super}} | Post Detail {% endblock %}

{% block post_username %}
<li class="nav-item">
	<a class="btn btn-outline-success" href="{% url 'posts:list' %}"> {{ instance.title|truncatechars:20 }} </a>
</li>
{% endblock post_username %}

{% block content %}
	<!-- Encabezado -->
	<div class="row">
		<!-- Titulo -->
		<div class="col-xs-7">
			<h2 class="title-post"> {{ title }} </h2>
		</div>
		<!-- Botones -->
		<div class="col-xs-5 btn-group" role="group">
			<!-- Volver a la lista de post -->
			<a href="{% url 'posts:list' %}">
				<button class="btn-post" type="button" data-toggle="tooltip" data-placement="bottom" title="Volver">
					<i class="fa fa-arrow-left fa-2x" aria-hidden="true"></i>
				</button>
			</a>
			{% if request.user.is_authenticated %}
			<!-- crear un nuevo post -->
			<a href="{% url 'posts:create' %}">
				<button class="btn-post" type="button" data-toggle="tooltip" data-placement="bottom" title="Crear">
					<i class="fa fa-pencil fa-2x" aria-hidden="true"></i>
				</button>
			</a>
				{% if request.user == instance.author %}
				<!-- Editar el post -->
				<a href="{% url 'posts:update' id=instance.id %}">
					<button class="btn-post" type="button" data-toggle="tooltip" data-placement="bottom" title="Editar">
						<i class="fa fa-newspaper-o fa-2x" aria-hidden="true"></i>
					</button>
				</a>
				<!-- Eliminar el post -->
				<button class="btn-post" type="button" data-toggle="modal" data-target="#ModalButtonDelete" data-placement="bottom" title="Eliminar">
					<i class="fa fa-trash fa-2x" aria-hidden="true"></i>
				</button>
				{% endif %}
			{% endif %}
		</div>
		<!-- End Buttons -->
	</div>
	<!-- Contenido -->
	<br>
	<div class="row container-fluid">
		<div class="col-xs-6">
			<div class="card" style="max-width:400px;">
				{% if instance.image %}
				<img 
				class="card-img-top rounded mx-auto d-block" 
				src="{{ instance.image.url }}" 
				alt="Card image cap" 
				style="">
				{% endif %}
			</div>
		</div>
		<div class="col-xs-6">
			<div class="card">
				<div class="card-body">
					<div class="card-title">
						<div class="row">
							<div class="col-xs-7">
								<h4 class="title-post"
								style="background-color: #343a40;">{{ instance.title }}</h4>
							</div>
							<div class="col-xs-5 btn-group" role="group">
								<button type="button" 
								data-toggle="modal" 
								data-target="#ModalCreateComment" 
								data-placement="bottom" 
								title="Añadir Comentario"
								class="btn btn-dark">
									<i class="fa fa-comment" aria-hidden="true"></i>	
								</button>
							</div>
						</div>
					</div>
					<!-- Contenido del post -->
					<p class="card-text"> SLUG: {{ instance.slug }} </p>
					<div class="content-markdown"> {{ instance.content }} </div>
					<!-- Si es un borrador -->
					{% if instance.draf %}
						<p class="card-text">
							<small class="text-muted">  
								<span style="color:red;"> Borrador </span> 
							</small>
						</p>    
					{% endif %}
					<!-- Fechas del post -->
					<p class="card-text"><small class="text-muted">Fecha de Creación: {{ instance.timestamp }} </small></p>
					<p class="card-text"><small class="text-muted">Fecha de Actualización: {{ instance.updated }} </small></p>
					<p class="card-text">
						<small class="text-muted">
							<span style="color:blue;"> Fecha de Publicación: {{ instance.publish }}  </span>
						</small>
					</p>
					<p class="card-text">
						<small> Tiempo de Lectura: 
							{% if instance.read_time|time:"i" <= "1" %} < 1 minuto
							{% elif instance.read_time|time:"i" < "10" %} < 10 minutos
							{% else %} {{ instance.read_time|time:"i" }} minutos
							{% endif %}
						</small> 
					</p>
					<!-- Nombre del usuario -->
					{% if instance.author.get_full_name %}
					<!-- Nombre completo -->
					<h5 class="card-text"> & {{ instance.author.get_full_name|capfirst }} </h5>
					{% else %}
					<!-- Nombre de usuario -->
					<h5 class="card-text"> & {{ instance.author }} </h5>
					{% endif %}	
				</div>
			</div>
		</div>
	</div>
	<br>
	<!-- Modal Button -->
	<div id="ModalButtonDelete" class="modal fade" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header" style="background-color: #dc3545; text-align: center;">
					<h4 class="" style="color:white;">Advertencia!!!</h4>            
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>
				<div class="modal-body">
					<h5>¿Está seguro de Eliminar este post?</h5>
				</div>
				<div class="modal-footer">
					<a href="{% url 'posts:delete' id=instance.id %}">	
						<button class="btn btn-danger">Aceptar</button>
					</a>
					<button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">Cerrar</button>
				</div>
			</div>
		</div>
	</div>
	<!-- End Modal Buttons -->

	<!-- Modal Create Comment -->
	<div id="ModalCreateComment" class="modal fade" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header" style="color:white; background-color: #007bff; border-radius: .25rem;">
					<h4> Comentar el Post: {{ instance.title|capfirst }} </h4>
				</div>
				<!-- Crea Comentarios -->
				{% if request.user.is_authenticated %}
				<div class="modal-body">
					<form action="." method="POST">
						{% csrf_token %}
						{{ comment_form|crispy }}
						<input type="submit" value="Guardar Comentario"
						class="btn btn-primary">
						<button type="button" class="btn btn-warning btn-sm" data-dismiss="modal">Cerrar</button>
					</form>
				</div>
				{% else %}
					<p> Debes iniciar sesión para crear un comentario </p>
					<button type="button" class="btn btn-success btn-sm" data-dismiss="modal">Cerrar</button>
				{% endif %}
			</div>
		</div>
	</div>
	<!-- End Modal Comment -->

	<!-- Modal Reply Comment -->
	<div class="modalreply">
		<div id="ModalReplyComment" class="modal fade" role="dialog">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header"
					style="color:white; background-color: #007bff; border-radius: .25rem;">
						<div class="row">
							<div class="container-fluid">
								<h4> Replica al comentario del Post:</h4>
								<h4> {{ instance.title|capfirst }}  </h4>
							</div>
						</div>
					</div>
					<!-- Crea Comentarios -->
					<div class="modal-body">
						{% if request.user.is_authenticated %}
						<form action="." method="POST">
							{% csrf_token %}
							{{ comment_form|crispy }}
							<input type="hidden" name="parent_id" value=" {{ comment.id }} ">
							<input type="submit" value="Replicar Comentario"
							class="btn btn-primary">
							<button type="button" class="btn btn-warning btn-sm" data-dismiss="modal">Cerrar</button>
						</form>
						{% else %}
							<p> Debes iniciar sesión para crear un comentario </p>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Modal Comment -->
	
	{% if comments %}
	<!-- Comentarios -->
	<div 
	style="margin-left: 0px; margin-right: 30px; padding-top: 10px;background-color: #eae6e6bd">
		<!-- Muestra Comentarios -->
		<div class="col-sm-12">

			<!-- Titulo -->
			<h2 class="lead" 
			style="padding-left:20px;text-transform: uppercase;">
				Comentarios
			</h2>
			<!-- Comentarios -->
			<div class="row">
				{% for comment in comments %}
					<div class="col-md-12" style="border-top: 1px solid #d4cbcb">
						<blockquote>
							<!-- Comentario Padre -->
							<p> {{ comment.content }} </p>
							<small style="color:#483f3f; margin: 0 20px">
								via & {{ comment.author|capfirst }}  |  {{ comment.timestamp|timesince }}
								{% if comment.children.count > 0 %}| {{ comment.children.count }} Comentario{% endif %}{% if comment.children.count > 1 %}s{% endif %}
								| <a href="#" class="comment_reply_btn" style="color:#007bff;">Responder</a>
								| <a href='{{ comment.get_absolute_url }}'>Detalles</a>
							</small>
							<!-- Replica de Comentarios -->
							<div class="comment_reply" style="display:none;">
								{% for child_comment in comment.children %}							
									<blockquote style="padding-left:25px; margin: 0 30px; background-color:#d4cbcb;border-radius:2px;">
										<p> {{ child_comment.content }} </p>
										<p>
											<small style="color:#007bff;">
												via & {{ child_comment.author|capfirst }}  |  {{ child_comment.timestamp|timesince }} 
											</small>
										</p>
									</blockquote>
								{% endfor %}
								<div class="container">
									{% if request.user.is_authenticated %}
									<form action="." method="POST">
										{% csrf_token %}
										{{ comment_form|crispy }}
										<input type="hidden" name="parent_id" value=" {{ comment.id }} ">
										<input type="submit" value="Replicar Comentario"
										class="btn btn-primary">
									</form>
									{% else %}
										<p> Debes iniciar sesión para crear un comentario </p>
									{% endif %}
								</div>
							</div>
						</blockquote>
						<!-- FIN de Comentarios -->
					</div>
				{% endfor %}
			</div>
		</div>
		<!-- Fin Muestra Comentarios -->
	</div>
	{% endif %}


	{% comment "Redes Sociales" %}
	<!-- Redes sociales -->
	{% include 'socialnetwork.html' %}
	{% endcomment %}

{% endblock %}

<script>
	{% block script %}
	// muestra los comentarios
	$(".comment_reply_btn").on("click",function(e) {
		e.preventDefault();
		$(this).parent().next(".comment_reply").fadeToggle("fast", "linear");
	});
	{% endblock script %}
</script>